spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/carManagement
    username: postgres
    password: 1234

  mvc:
    pathmatch:
      matching-strategy: "path-pattern-parser"
  jpa:
  hibernate:
    ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

